# The flags generated by E2 Studio IDE (RX65N Cloud Kit example project)
set(COMPILER_FLAGS_COMMON "\
-ffunction-sections \
-fdata-sections \
-Wstack-usage=512 \
-mcpu=rx64m \
-misa=v2 \
-mlittle-endian-data \
-Wa,-adlnh=\"$(basename $(notdir $<)).lst\" \
-MMD \
-MP \
")

# linker flags
set(LINKER_FLAGS_COMMON "\
-Wl,--start-group -lm -lc -lgcc -Wl,--end-group -nostartfiles \
-T../SDK/Renesas_RX65N-CK/linker_script.ld \
-static \
-Wl,-e_PowerON_Reset \
-Wl,-M=binary.map \
")

# set flags for Assembler
set(CMAKE_ASM_FLAGS "-g2 -O0 ${COMPILER_FLAGS_COMMON}")

# set flags for C compiler
set(CMAKE_C_FLAGS "-g2 -O0 -std=gnu99 ${COMPILER_FLAGS_COMMON}")

# set flags for C++ compiler
set(CMAKE_CXX_FLAGS "-g2 -O0 ${COMPILER_FLAGS_COMMON}")

# set flags for linker
set(CMAKE_EXE_LINKER_FLAGS "${LINKER_FLAGS_COMMON}")
